site_name: Intro to HPC (Deep Learning)

site_author: NeSI
site_dir: public
site_url: "https://nesi.github.io/hpc-intro-dl"
site_description: "Introduction to running deep learning code on NeSI"

repo_name: nesi/hpc-intro-dl
repo_url: https://github.com/nesi/hpc-intro-dl

exclude_docs: |
  .ipynb_checkpoints

theme:
  name: material

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - smarty
  - sane_lists
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - index.md
  - setup.md
  - install.md
  - submit.md
  - monitor.md
  - interact.md
